# Change these first
owner: megamovnetwork # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Dedicated server D1-RBX4
    url: $D1_RBX4
  - name: Node Cloud
    url: $NODE_CLOUD
  - name: Node Teamspeak
    url: $NODE_TEAMSPEAK
  - name: Node Webhosting
    url: $NODE_WEBHOSTING
  - name: Node Web
    url: $NODE_WEB
   
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.megamov.fr
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/megamovnetwork/upptime/master/megamov.png
  name: MeGaMoV
  introTitle: "**MeGaMoV** infrastructure"
  introMessage: Summary
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
